--liquibase formatted sql

--changeset yuzhi:001-create-lottery-campaign
CREATE TABLE lottery_campaign (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_code       VARCHAR(64) NOT NULL,
    name                VARCHAR(128) NOT NULL,
    status              VARCHAR(20) NOT NULL,
    max_draws_per_user  INTEGER NOT NULL,
    starts_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    ends_at             TIMESTAMP WITH TIME ZONE NOT NULL,
    version             BIGINT NOT NULL DEFAULT 0,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_lottery_campaign_code UNIQUE (campaign_code),
    CONSTRAINT ck_campaign_status CHECK (status IN ('DRAFT', 'ACTIVE', 'PAUSED', 'ENDED')),
    CONSTRAINT ck_campaign_draw_limit CHECK (max_draws_per_user > 0),
    CONSTRAINT ck_campaign_period CHECK (ends_at > starts_at)
);

CREATE INDEX idx_campaign_status_period ON lottery_campaign (status, starts_at, ends_at);

--changeset yuzhi:002-create-lottery-prize
CREATE TABLE lottery_prize (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_id         BIGINT NOT NULL,
    prize_code          VARCHAR(64) NOT NULL,
    name                VARCHAR(128) NOT NULL,
    prize_type          VARCHAR(20) NOT NULL,
    probability         NUMERIC(8, 7) NOT NULL,
    total_stock         BIGINT NOT NULL DEFAULT 0,
    remaining_stock     BIGINT NOT NULL DEFAULT 0,
    display_order       INTEGER NOT NULL DEFAULT 0,
    enabled             BOOLEAN NOT NULL DEFAULT TRUE,
    version             BIGINT NOT NULL DEFAULT 0,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_prize_campaign FOREIGN KEY (campaign_id) REFERENCES lottery_campaign (id),
    CONSTRAINT uk_prize_campaign_code UNIQUE (campaign_id, prize_code),
    CONSTRAINT ck_prize_type CHECK (prize_type IN ('PRIZE', 'NO_PRIZE')),
    CONSTRAINT ck_prize_probability CHECK (probability >= 0 AND probability <= 1),
    CONSTRAINT ck_prize_stock CHECK (total_stock >= 0 AND remaining_stock >= 0 AND remaining_stock <= total_stock),
    CONSTRAINT ck_no_prize_stock CHECK (prize_type <> 'NO_PRIZE' OR (total_stock = 0 AND remaining_stock = 0))
);

CREATE INDEX idx_prize_campaign_enabled ON lottery_prize (campaign_id, enabled, display_order);

-- At most one NO_PRIZE row per campaign. Before activation, the service must also
-- validate its presence and that all enabled probabilities sum to exactly 1.0000000.
CREATE UNIQUE INDEX uk_prize_one_no_prize_per_campaign
    ON lottery_prize (campaign_id) WHERE prize_type = 'NO_PRIZE';

--changeset yuzhi:003-create-lottery-event
CREATE TABLE lottery_event (
    event_id            UUID PRIMARY KEY,
    request_id          VARCHAR(128) NOT NULL,
    campaign_id         BIGINT NOT NULL,
    user_id             VARCHAR(128) NOT NULL,
    event_type          VARCHAR(64) NOT NULL,
    draw_count          INTEGER NOT NULL,
    status              VARCHAR(20) NOT NULL,
    payload             JSONB NOT NULL,
    result_payload      JSONB,
    retry_count         INTEGER NOT NULL DEFAULT 0,
    next_retry_at       TIMESTAMP WITH TIME ZONE,
    published_at        TIMESTAMP WITH TIME ZONE,
    processed_at        TIMESTAMP WITH TIME ZONE,
    version             BIGINT NOT NULL DEFAULT 0,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_event_campaign FOREIGN KEY (campaign_id) REFERENCES lottery_campaign (id),
    CONSTRAINT uk_lottery_event_request UNIQUE (request_id),
    CONSTRAINT ck_event_draw_count CHECK (draw_count > 0),
    CONSTRAINT ck_event_retry_count CHECK (retry_count >= 0),
    CONSTRAINT ck_event_status CHECK (status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'PUBLISHED'))
);

CREATE INDEX idx_event_outbox_polling ON lottery_event (status, next_retry_at, created_at);
CREATE INDEX idx_event_campaign_user ON lottery_event (campaign_id, user_id, created_at);
