--liquibase formatted sql

--changeset yuzhi:004-create-lottery-user-quota
CREATE TABLE lottery_user_quota (
    campaign_id BIGINT NOT NULL,
    user_id VARCHAR(128) NOT NULL,
    used_draws INTEGER NOT NULL DEFAULT 0,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (campaign_id, user_id),
    CONSTRAINT fk_quota_campaign FOREIGN KEY (campaign_id) REFERENCES lottery_campaign (id),
    CONSTRAINT ck_quota_used_draws CHECK (used_draws >= 0)
);

--changeset yuzhi:005-create-lottery-draw
CREATE TABLE lottery_draw (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id UUID NOT NULL,
    draw_sequence INTEGER NOT NULL,
    campaign_id BIGINT NOT NULL,
    user_id VARCHAR(128) NOT NULL,
    prize_id BIGINT,
    prize_code VARCHAR(64),
    prize_name VARCHAR(128) NOT NULL,
    won BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_draw_event FOREIGN KEY (event_id) REFERENCES lottery_event (event_id),
    CONSTRAINT fk_draw_campaign FOREIGN KEY (campaign_id) REFERENCES lottery_campaign (id),
    CONSTRAINT fk_draw_prize FOREIGN KEY (prize_id) REFERENCES lottery_prize (id),
    CONSTRAINT uk_draw_event_sequence UNIQUE (event_id, draw_sequence),
    CONSTRAINT ck_draw_sequence CHECK (draw_sequence > 0)
);

CREATE INDEX idx_draw_campaign_user ON lottery_draw (campaign_id, user_id, created_at);
